### ISSUE TITLE
OpenResty 1.25.3.2

### ISSUE THREAD

**Issue by cubicdaiya** [cubicdaiya/nginx-build#151]
Regarding https://github.com/cubicdaiya/nginx-build/pull/149, openresty-1.25.3.2 hasn't been released yet?

- https://openresty.org/en/
- https://github.com/openresty/openresty/releases

**Comment by catatsuy** [comment]
The tag for OpenResty v1.25.3.2 exists, but it is not released yet and I cannot download it. Also, v1.25.3.1 has a bug that makes it not possible to compile with PCRE2, so it is hard to add to CI. I think to revert for now and add it to CI when it is released. @cubicdaiya

**Comment by xaizek** [comment]
Offtopic, so feel free to remove this comment, posting here because stuff in https://github.com/cubicdaiya/dtl seems to be ignored for a while and this is recent.  @cubicdaiya, please hit merge button on https://github.com/cubicdaiya/dtl/pull/18 or https://github.com/cubicdaiya/dtl/pull/22 to fix a build issue.
