### ISSUE TITLE
error: invalid option "--add-dynamic"

### ISSUE THREAD

**Issue by ojos** [cubicdaiya/nginx-build#6]
以下のコマンドでエラーがでました。

$ git clone https://github.com/vkholodkov/nginx-upload-module.git
$ nginx-build -d work -clear -openssl -pcre --add-module=nginx-upload-module --prefix=/Users/ojos/sandbox/nginx
nginx-build: 0.7.2
Compiler: gc go1.5.3
2016/03/24 13:07:33 Download nginx-1.9.12.....
2016/03/24 13:07:33 Download pcre-8.38.....
2016/03/24 13:07:33 Download openssl-1.0.2g.....
2016/03/24 13:07:36 Extract nginx-1.9.12.tar.gz.....
2016/03/24 13:07:40 Extract pcre-8.38.tar.gz.....
2016/03/24 13:07:46 Extract openssl-1.0.2g.tar.gz.....
2016/03/24 13:07:47 Generate configure script for nginx-1.9.12.....
2016/03/24 13:07:47 Configure nginx-1.9.12.....
2016/03/24 13:07:47 Failed to configure nginx-1.9.12
./configure: error: invalid option "--add-dynamic"
2016/03/24 13:07:47 exit status 1

--add-moduleオプションが--add-dynamicオプションに変換されてconfigureに渡されているのではないかと推測しているのですが、goが不得手で問題箇所をソースから見つけることができないため、報告だけさせていただきました。

**Comment by cubicdaiya** [comment]
Hi @ojos,

Thank you for the report. As fixed in https://github.com/cubicdaiya/nginx-build/commit/0e7daed5a5455bc393e6bb28a276a4e2e0ec4793, please check it. （But, nginx-upload-module is not maintained for a long while. So the compilation would be still maybe failed.）

BTW, write the issue in English if possible, please.

**Comment by cubicdaiya** [comment]
Released bugfixed version (0.7.3) -> https://github.com/cubicdaiya/nginx-build/releases/tag/v0.7.3
